[package]
name = "minimisation_of_multiplicity_tree_automata"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.1"
trees = "0.4.2"
log = "0.4"
env_logger = "0.10.1"
clap = { version = "4.4.10", features = ["derive"] }
